### ISSUE TITLE
Police Station Cinematic

### ISSUE THREAD

**Issue by dwesty23** [dwesty23/golden_hours#11]
Once you hit new game, Sophie is in a police station (seperate scene), a convo plays out between her and a cop, once convo is over, cut to sophie outside the station (main map)

- cinematic scene
- text bubbles
- cut back to main

**Comment by dwesty23** [comment]
Working with Bhavik on #10

**Comment by hortojac** [comment]
Update dialogue where the player can push space to play out the entire dialogue for the character. Clicking space again goes to the next dialogue text.
Animate Sophie walking towards the cop.
Add player faces for the chatracter talking.
Add police officer font for when they speak.
