### ISSUE TITLE
Importing real assets

### ISSUE THREAD

**Issue by dwesty23** [dwesty23/golden_hours#13]
After we incorporate #12 , we will want to switch out backgrounds/assets to be the official ones, and create our full map.

**Comment by gdlahood** [comment]
yay!

**Comment by dwesty23** [comment]
start screen ->
- start screen with options, without options and the text
- menu (low priority)

general assets ->
- maya
- sophie
- background
- dialogue bubbles
- clocks (hex values for the color scheme)
- character faces for dialogue

police station cinematic ->
- cop
- police station background

meeting may (low priority) ->
- game controls image where Maya explains the controls to Sophie

**Comment by bhavik-goplani** [comment]
Resolution should scale - 1080p - no blue borders around
