### ISSUE TITLE
Milkshake puzzle

### ISSUE THREAD

**Issue by bhavik-goplani** [dwesty23/golden_hours#23]
Once the first milkshake puzzle is completed, it goes towards the right and disappears and the new milkshake appears for the next puzzle.
One has to be empty.
Use the Pre-built asset - https://assetstore.unity.com/packages/templates/packs/sliding-tile-puzzle-game-41798#reviews

**Comment by dwesty23** [comment]
just add the first 3x3 puzzle at a bare minimum. Have the character move a bit, touch a button with e, and the puzzle launches. :) good luck
