### ISSUE TITLE
Time Mechanic

### ISSUE THREAD

**Issue by hortojac** [dwesty23/golden_hours#7]

**Comment by dwesty23** [comment]
3 clocks, game ends when they run out, probably have them set to 30mins? for now...

**Comment by dwesty23** [comment]
reference image:
![Image](https://github.com/dwesty23/golden_hours/assets/120140940/4989b7b7-f7c4-4256-b161-62823eaede67)


time spent -> R: 165 G: 102 B: 92
time left -> R: 221 G: 192 B: 98

**Comment by dwesty23** [comment]
done?
