### ISSUE TITLE
Test Camera/Lighting

### ISSUE THREAD

**Issue by dwesty23** [dwesty23/golden_hours#8]
- See if it's possible to map light to camera to solve night/day shifting

**Comment by bhavik-goplani** [comment]
happening gg

**Comment by dwesty23** [comment]
https://youtu.be/nkgGyO9VG54?si=0meC6a87IQ1gMHy2

https://youtu.be/ihurRMKz2es?si=BJ3IjdbL2mfxEFIx

**Comment by dwesty23** [comment]
Tested, works, and we will implement. I'm going to forget about my branch and try to implement into Suhaan's scene switching branch to make sure it will work as we transition between scenes. 😍
